/**
 * This file is generated by data-enhancer
 * The code is all auto-generated and carefully modify it
 */
import NotNull from 'data-enhancer';
import e from './e';


export default class {
    constructor (obj = {}) {
        const {
            a,
            b,
            c,
            e,
            
        } = obj;

        this._a = a;
        this._b = b;
        this._c = c;
        this._e = e;
        
    }

    
    @NotNull('sdfsdf')
    get a() { return this._a; }
    set a (value) { this._a = value; }
    
    @NotNull('sfs')
    get b() { return this._b; }
    set b (value) { this._b = value; }
    
    @NotNull('test')
    get c() { return this._c; }
    set c (value) { this._c = value; }
    
    @NotNull(new e())
    get e() { return this._e; }
    set e (value) { this._e = value; }
    
}
