/**
 * This file is generated by data-enhancer
 * The code is all auto-generated and carefully modify it
 */
import NotNull from 'data-enhancer';


export default class {
    constructor (obj = {}) {
        const {
            a,
            b,
            
        } = obj;

        this._a = a;
        this._b = b;
        
    }

    
    @NotNull('haha')
    get a() { return this._a; }
    set a (value) { this._a = value; }
    
    @NotNull('test')
    get b() { return this._b; }
    set b (value) { this._b = value; }
    
}
