/**
 * This file is generated by data-enhancer
 * The code is all auto-generated and carefully modify it
 */
import NotNull from 'data-enhancer';
import d from './d';


export default class {
    constructor (obj = {}) {
        const {
            a,
            b,
            c,
            d,
            
        } = obj;

        this._a = a;
        this._b = b;
        this._c = c;
        this._d = d;
        
    }

    
    @NotNull(444)
    get a() { return this._a; }
    set a (value) { this._a = value; }
    
    @NotNull('adf')
    get b() { return this._b; }
    set b (value) { this._b = value; }
    
    @NotNull([1,2,3])
    get c() { return this._c; }
    set c (value) { this._c = value; }
    
    @NotNull(new d())
    get d() { return this._d; }
    set d (value) { this._d = value; }
    
}
